export const Productdata = [
  {
    id: 'transfer cart agv',
    title: "TRANSFER CART & AGV'S",
    url: 'transfer-cart-agv',
    desciription:
      'FADA develops innovative solutions for the transfer of heavy and geometrically difficult loads with its Transfer Carts, and offers special solutions for sensitive and efficient transport. It is used in the transfer of coils, turbines and blades in the wind energy sector, transformers, molds, sheet metal, large casting parts and various machine parts in industrial plants.They are ergonomic, economical and have the necessary safety equipment with a special design for the needs. They are produced in accordance with the Occupational Health and Safety Management Rules, and when an object or a moving object appears in front of it in the direction it is moving, it is detected by the laser sensors, stops the vehicle movement and reduces the risks of accidents.Industrial transfer carts manufactured by Fada Engineering are basically divided into three main groups. These are rail transfer carts moving in a straight line on the rail, low maneuverability battery powered transfer carts by steering only the front wheels and high maneuverability battery transfer carts that can move in any desired direction by steering all wheels. While the battery powered transfer carts can go in any direction desired, they have various mobility capabilities such as carousel movement, crab movement, diagonal movement. These heavy-duty transport vehicles can be diversified as diesel or battery powered according to the power source.',
    imgUrl: '/products/araba.png',
    product: [
      {
        id: '0003',
        type: 'transfer cart',
        title: 'multidirectional steering battery powered transfer cart(MTC)',
        description:
          'Otonom transfer arabaları düzenli iş akışına sahip işletmelerde sürekliliği sağlamak adına tercih edilen ağır yük transfer arabalarıdır.',
        imgUrl: '/transferarabasi/multi.jpg',
        propert: [
          'Capacity: 5 ton to 100 tons',
          'Speed: Up to 30 m/min',
          'Steering: All-Wheel steering',
          'Movements: 360° rotation (Carousel) and crab movement (horizontal and diagonal movements)',
          'Wheel Type: Rubber / Polyurethane',
          'Control: Remote Control / Autonomous',
          'Power Source: Battery / Diesel',
          'Motors: PMAC / AC high efficiency motors',
          'Loading Table: On request',
          'Security: Laser and ultrasonic sensors, bumpers',
          'Dimensions: On request',
        ],
        certification: [],
      },
      {
        id: '0001',
        type: 'transfer cart',
        title: 'rail transfer cart',
        description:
          'Otonom transfer arabaları düzenli iş akışına sahip işletmeOtonom transfer arabaları düzenli iş akışına sahip işletmeOtonom transfer arabaları düzenli iş akışına sahip işletmelerde sürekli Otonom transfer arabaları düzenli iş akışına sahip işletmelerde sürekliOtonom transfer arabaları düzenli iş akışına sahip işletmelerde sürekliliği sağlamak adına tercih edilen ağır yük transfer arabalarıdır.',
        imgUrl: '/transferarabasi/ray.png',
        propert: [
          'Capacity: 1 ton to 200 tons',
          'Speed: Up to 60 m/min',
          'Wheel Type: Steel / Casting wheel',
          'Control: Remote control / Autonomous',
          'Power Source: Spring drum, Bus-Bar, Cable carrier, Battery, Diesel',
          'Motors: AC / DC electric motor, Hydraulic / Pneumatic actuator',
          'Loading Table: On request',
          'Security: Laser and ultrasonic sensors, bumpers',
          'Dimensions: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0002',
        type: 'transfer cart',
        title: 'front wheel steering battery powered transfer cart',
        description: '',
        imgUrl: '/transferarabasi/front.png',
        propert: [
          'Capacity: 5 ton to 100 tons',
          'Speed: Up to 30 m/min',
          'Steering: Front wheel steering',
          'Wheel Type: Rubber / Polyurethane',

          'Control: Remote control / Autonomous',
          'Power Source: Battery / Diesel',
          'Motors: PMAC / AC high efficiency motors',
          'Loading Table: On request',
          'Security: Laser and ultrasonic sensors, bumpers',
          'Dimensions: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
    ],
  },
  {
    id: 'automated stroge systems',
    title: 'AUTOMATED STORAGE SYSTEMS (ASRS)',
    url: 'automated-stroge-systems',
    desciription:
      'Thanks to the Automatic Storage Systems it has produced, FADA Engineering ensures the ergonomic, precise and safe storage of profiles, sheets, pipes, panels, heavy and geometrically difficult parts in industrial facilities. With the Warehouse Management Software it has developed, it offers various solutions for the automatic storage of heavy materials in your warehouses with minimum labor and maximum efficiency. Automatic storage systems, with their long and high structure, save space in the facilities, reduce your costs by automatically performing material transfer and material unloading within seconds. With its engineers who are experts in Storage Systems, FADA offers ideal storage solutions by closely following up-to-date technologies and developing innovative solutions according to your storage needs.',

    imgUrl: '/products/depolama.png',
    product: [
      {
        id: '0001',
        type: 'automated stroge systems',
        title: 'single tower automated stroge system (STSS)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: Up to 200 tons',
          'Shelf Capacity: Up to 5 tons',
          'Shelf Dimensions: 1 x 2 m / 1,5 x 3 m / 2 x 4 m / 2 x 6 m / On request',
          'Control: User-Friendly touch screen',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        options: [
          'Inventory management software',
          'ERP ıntegration',
          'Secondary loading / Unloading compartment',
          'Anti-Fall safety system',
          'Load-Cell system',
        ],
      },
      {
        id: '0002',
        type: 'automated stroge systems',
        title: 'double tower automated stroge system (DTSS)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: Up to 400 tons',
          'Shelf Capacity: Up to 5 tons',
          'Shelf Dimensions: 1 x 2 m / 1,5 x 3 m / 2 x 4 m / 2 x 6 m / On request',
          'Control: User-Friendly touch screen',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        options: [
          'Inventory management software',
          'ERP ıntegration',
          'Secondary loading / Unloading compartment',
          'Anti-Fall safety system',
          'Load-Cell System',
        ],
      },
      {
        id: '0003',
        type: 'automated stroge systems',
        title: ' multi-tower automated stroge system (MTSS)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: Up to 1000 tons',
          'Shelf Capacity: Up to 5 tons',
          'Shelf Dimensions: 1 x 2 m / 1,5 x 3 m / 2 x 4 m / 2 x 6 m / On request',
          'Control: User-Friendly touch screen',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        options: [
          'Inventory management software',
          'ERP ıntegration',
          'Secondary loading / Unloading compartment',
          'Anti-Fall safety system',
          'Load-Cell System',
        ],
      },
      {
        id: '0004',
        type: 'automated stroge systems',
        title: ' horizontel automated stroge system (HSS)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: Up to 1000 tons',
          'Shelf Capacity: Up to 5 tons',
          'Shelf Dimensions: Up to 10 m',
          'Control:Semi or fully automatic control / ERP ıntegration- Database and inventory management software',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0005',
        type: 'automated stroge systems',
        title: ' sheet metal stroge system (SMSS)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: Up to 40 tons',
          'Shelf Capacity: Up to 3 tons',
          'Shelf Dimensions: 1 x 2 m / 1,5 x 3 m / 2 x 4 m / On request',
          'Control:Semi or fully automatic control / ERP ıntegration- Database and inventory management software',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0006',
        type: 'automated stroge systems',
        title: ' profil stroge system (PSS)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: Up to 500 tons',
          'Shelf Capacity: Up to 3 tons',
          'Shelf Dimensions: 0,4 x 0,4 x 6 m / On request',
          'Control: Manual',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
    ],
  },
  {
    id: 'positioners and rotating solutions',
    title: 'POSITIONERS AND ROTATING SOLUTIONS',
    url: 'positioners-and-rotating-solutions',
    desciription:
      "FADA Engineering, with its Rotation and Positioning Systems, designs smart, flexible, ergonomic and safe solutions for its customers to rotate heavy and geometrically difficult workpieces. The rotators, chain turning systems, turning devices and welding positioners produced in this product group precisely position the workpieces and speed up the workflow. With its ergonomic and reliable structure, it offers system solutions suitable for customers' rotation needs.",
    imgUrl: '/products/dondurme.png',
    product: [
      {
        id: '0001',
        type: 'posıtıoners and rotating solutıons',
        title: 'welding positioner(wp)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: Up to 30 tons',
          'Speed: Up to 1.5 rpm',
          'control: Manual / Automatic control , ERP integration',
          'Security: Laser scanner , Light curtains , Various sensors',
          'Design: On Request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0002',
        type: 'posıtıoners and rotating solutıons',
        title: 'load turning devices(ltd) ',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: Up to 50 tons',
          'Speed: Up to 3 rpm',
          'Control:  Wired / Remote control',
          'Security: Various sensors',
          'Design: On Request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0003',
        type: 'posıtıoners and rotating solutıons',
        title: 'chain rotator(cr) ',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: Up to 10 tons',
          'Speed: Up to 5 rpm',
          'Control:  Wired / Remote control',
          'Security: Various sensors',
          'Design: On Request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0004',
        type: 'posıtıoners and rotating solutıons',
        title: 'self-align rotators (sar)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: Up to 100 tons',
          'Speed:  100 - 1000 mm / min',
          'Kind Of Wheel: Polyurethane',
          'Control:  Wired / Remote control',
          'Security: Various sensors',
          'Design: On Request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0005',
        type: 'posıtıoners and rotating solutıons',
        title: 'chain rotator(cr) ',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: Up to 40 tons',
          'Speed: 0,1 - 1 rpm',
          'Control:  Wired / Remote control',
          'Security: Various sensors',
          'Design: On Request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
    ],
  },
  {
    id: 'intralogistics and conveyor solutions',
    title: 'INTRALOGISTICS & CONVEYOR SOLUTIONS',
    url: 'intralogistics-and-conveyor-solutions',
    imgUrl: '/products/konveyor.jpg',
    desciription:
      "FADA Engineering offers innovative, smart and ergonomic solutions for the needs of companies in various sectors in production and assembly lines, warehouses and paint shops, in terms of automatic transportation, distribution, transfer and product separation. Conveyor and Distribution systems; They are systems designed for the needs of our customers with their durability, reliability and ergonomic structure during loading, unloading and transportation. With our high quality engineering service, we make conveyor line installations suitable for the customer's product and process, and provide you with special innovative distribution solutions by providing economical and efficient work flows.'    imgUrl: '/yektemak.jpg",
    product: [
      {
        id: '0001',
        type: 'intralogistics and conveyor solutions',
        title: 'roller conveyor system (rcs)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: 2 ton/m',
          'Speed: Up to 60 m/min',
          'Roller Material: Electro-Galvanized, stainless steel, aluminum, painted roller',
          'Security: Various sensors',
          'Dimensions: On Request',
          'Application Areas: Manufacturing, assembly lines, paint shops and warehouses',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0002',
        type: 'intralogistics and conveyor solutions',
        title: 'belt conveyor system (bcs)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: 200 kg/m ',
          'Speed: Up to 60 m/min',
          'Band Material: PVC, PU, Rubber',
          'Security: Various sensors',
          'Dimensions: On Request',

          'Application Areas: Manufacturing, assembly lines, paint shops and warehouses',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0003',
        type: 'intralogistics and conveyor solutions',
        title: 'chain conveyor system (ccs)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: 2 ton/m ',
          'Speed: Up to 20 m/min',
          'Construction: Electro-Galvanized, stainless steel, aluminum',
          'Security: Various sensors',
          'Dimensions: On Request',
          'Application Areas: Manufacturing, assembly lines, paint shops and warehouses',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0004',
        type: 'intralogistics and conveyor solutions',
        title: 'vertical conveyor system (ccs)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: [
          'Capacity: 500 kg/palet ',
          'Lifting Speed: Up to 10 m/min',
          'Lift Height: Up to 15 m',
          'Construction: Electro-Galvanized, stainless steel, aluminum',
          'Security: Various sensors',
          'Dimensions: On Request',
          'Application Areas: Manufacturing, assembly lines, paint Shops and warehouses',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
    ],
  },
  {
    id: 'cranes lifting and handling equiments',
    title: 'CRANES / LIFTING & HANDLING EQUIPMENTS ',
    url: 'cranes-lifting-and-handling-equiments',
    imgUrl: '/products/sdasd.jpg',
    desciription:
      'FADA Engineering offers smart solutions for you to safely lift your heavy and geometrically difficult parts. In this context, Jib Cranes, Light Crane Systems, C Hooks, I Type Traverses, H Type Traverses and Coil Tongs; With its ergonomic, functional and economic structure, we respond to the increasing demands of our customers in many industrial sectors. With our high quality engineering service, we offer special solutions that will make the workflow most efficient according to the needs and processes of our customers.',
    product: [
      {
        id: '0001',
        type: 'cranes lifting and handling equiments',
        title: 'jib cranes(jc)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: ['Capacity: 5 ton', 'Design  : On Request'],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        TechnicialSpecifications: [
          '180 / 270 / 360 degree rotation feature.',
          '3000 - 6000 mm arm length',
          'Electric or manual rotation movement',
          'Wall or floor mounting',
          'Wired / remote control',
          'German origin lifting machine',
          'Warning system',
          'Heavy duty design',
        ],
      },
      {
        id: '0002',
        type: 'cranes lifting and handling equiments',
        title: 'light weight crane system (lwcs)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: ['Capacity: up to 2 tons', 'Design: On Request'],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        TechnicialSpecifications: [
          '3000 - 10000 mm bridge span',
          'Three axes electrically driven movement',
          'Wired / remote control',
          'German origin lifting machine',
          'Illuminated audible warning system',
          'Heavy duty design',
        ],
      },
      {
        id: '0003',
        type: 'cranes lifting and handling equiments',
        title: 'coil tongs (ct)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: ['Capacity: up to 40 tons', 'Design: On Request'],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        TechnicialSpecifications: [
          'Electric or manual arm opening and closing',
          'Suitable for handling aluminum, steel and paper coils',
          'Safety sensors suitable for flexible operation',
          'Electric or manual rotation movement',
          'Wired or remote control',
          'Illuminated audible warning system',
          'Heavy duty design',
        ],
      },
      {
        id: '0004',
        type: 'cranes lifting and handling equiments',
        title: 'ı type traverse(ıtt)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: ['Capacity: 500 kg - up to 50 tons', 'Design: On Request'],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        Design: [
          "Customized design according to customer's crane hook size and request",
          'Adjustable or fixed I Type Traverses',
          'Heavy duty design',
        ],
      },
      {
        id: '0005',
        type: 'cranes lifting and handling equiments',
        title: 'h type traverse(htt)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: ['Capacity: 500 kg - up to 50 tons', 'Design: On Request'],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        Design: [
          "Customized design according to customer's crane hook size and request",
          'Adjustable or fixed H Type Traverses',
          'Heavy duty design',
        ],
      },
      {
        id: '0006',
        type: 'cranes lifting and handling equiments',
        title: 'c hooks (ch)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: ['Capacity: 500 kg - up to 50 tons', 'Design: On Request'],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        Design: [
          "Customized design according to customer's crane hook size and request",
          'Adjustable or fixed C Hooks',
          'Carrying stand',
          'Electric return feature',
          'Counterbalance weight',
          'Sensitive seating surface',
          'Heavy duty design',
        ],
      },
    ],
  },
  {
    id: 'ergonomic access platforms',
    title: 'ERGONOMIC ACCESS PLATFORMS',
    url: 'ergonomic-access-platforms',
    imgUrl: '/products/platform.png',

    desciription:
      "FADA Engineering; With the Pneumatic Access Platforms it has produced, it offers innovative, ergonomic and safe solutions to its customers' various access needs in production and assembly lines in many sectors such as aviation, automotive, logistics, railway systems, energy, shipyards, maritime, etc. These Access Platforms can be produced completely pneumatically or electrically controlled. We are able to produce flexible solutions thanks to fully pneumatic access platforms with Ex-Proof protection, ATEX approval and CE certificate in areas where the needs meet with dangerous gases such as paint shops, LPG/LNG filling facilities, etc. Our Pneumatic Access Platforms in production facilities where the needs do not meet with dangerous gases; It can be diversified as battery, electric, hydraulic or pneumatic according to customer needs. These access platforms can be produced with 3 axes movable according to the place of use and are offered to your service as Wall Type, Mobile Type and XL Type Platform according to your needs.s APPLICATION AREAS: Aerospace and Aviation Applications, Wind Turbines, Wind Blades; Trailer, Bus, Truck and Wagon Manufacturing Paint Shops, Applications in the Transformer Sector",
    product: [
      {
        id: '0001',
        type: 'ergonomic access platforms',
        title: 'wall type platform',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: ['Capacity: Single person. 150 kg capacity'],
        certification: ['OHS regulations', 'EN standards', 'CE certificated', 'Atex Approved'],
        TechnicialSpecifications: [
          'Movement in three axis',
          'Pneumatic joystick control valves',
          'Brake system for stable positioning',
          'Paint protected drive system',
          '6 - 12 bar compressed air supply',
          'Height stabilization bar for maintenance',
          'Inward opening safe door system',
          'Overweight safety system',
          'Anti-squeeze safety system',
          'Warning horn',
        ],
      },
      {
        id: '0001',
        type: 'ergonomic access platforms',
        title: 'jib cranes(jc)',
        description: '',
        imgUrl: '/a/dep.jpg',
        propert: ['Capacity: Single person. 150 kg capacity'],
        certification: ['OHS regulations', 'EN standards', 'CE certificated', 'Atex Approved'],
        TechnicialSpecifications: [
          'Movement in three axis',
          'Pneumatic joystick control valves',
          'Brake system for stable positioning',
          'Paint protected drive system',
          '6 - 12 bar compressed air supply',
          'Height stabilization bar for maintenance',
          'Inward opening safe door system',
          'Overweight safety system',
          'Anti-squeeze safety system',
          'Warning horn',
        ],
      },
    ],
  },
];
