export const Productdata = [
  {
    id: 'transfer cart agv',
    title: "TRANSFER CART & AGV'S",
    url: 'transfer-cart-agv',
    desciription:
      'FADA develops innovative solutions for the transfer of heavy and geometrically difficult loads with its Transfer Carts, and offers special solutions for sensitive and efficient transport. It is used in the transfer of coils, turbines and blades in the wind energy sector, transformers, molds, sheet metal, large casting parts and various machine parts in industrial plants.They are ergonomic, economical and have the necessary safety equipment with a special design for the needs. They are produced in accordance with the Occupational Health and Safety Management Rules, and when an object or a moving object appears in front of it in the direction it is moving, it is detected by the laser sensors, stops the vehicle movement and reduces the risks of accidents.Industrial transfer carts manufactured by Fada Engineering are basically divided into three main groups. These are rail transfer carts moving in a straight line on the rail, low maneuverability battery powered transfer carts by steering only the front wheels and high maneuverability battery transfer carts that can move in any desired direction by steering all wheels. While the battery powered transfer carts can go in any direction desired, they have various mobility capabilities such as carousel movement, crab movement, diagonal movement. These heavy-duty transport vehicles can be diversified as diesel or battery powered according to the power source.',
    imgUrl: '',
    product: [
      {
        id: '0003',
        type: 'transfer cart',
        title: 'multidirectional steering battery powered transfer cart(MTC)',
        description:
          'Otonom transfer arabaları düzenli iş akışına sahip işletmelerde sürekliliği sağlamak adına tercih edilen ağır yük transfer arabalarıdır.',
        imgUrl: 'https://yektamak.com/storage/media/2022/01/otonom-transfer-arabalari-1.jpg',
        propert: [
          'Capacity: 5 ton to 100 tons',
          'Speed: Up to 30 m/min',
          'Steering: All-Wheel steering',
          'Movements: 360° rotation (Carousel) and crab movement (horizontal and diagonal movements)',
          'Wheel Type: Rubber / Polyurethane',
          'Control: Remote Control / Autonomous',
          'Power Source: Battery / Diesel',
          'Motors: PMAC / AC high efficiency motors',
          'Loading Table: On request',
          'Security: Laser and ultrasonic sensors, bumpers',
          'Dimensions: On request',
        ],
        certification: [],
      },
      {
        id: '0001',
        type: 'transfer cart',
        title: 'rail transfer cart',
        description: '',
        imgUrl: 'https://yektamak.com/storage/media/2022/01/otonom-transfer-arabalari-1.jpg',
        propert: [
          'Capacity: 1 ton to 200 tons',
          'Speed: Up to 60 m/min',
          'Wheel Type: Steel / Casting wheel',
          'Control: Remote control / Autonomous',
          'Power Source: Spring drum, Bus-Bar, Cable carrier, Battery, Diesel',
          'Motors: AC / DC electric motor, Hydraulic / Pneumatic actuator',
          'Loading Table: On request',
          'Security: Laser and ultrasonic sensors, bumpers',
          'Dimensions: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0002',
        type: 'transfer cart',
        title: 'front wheel steering battery powered transfer cart',
        description: '',
        imgUrl: 'https://yektamak.com/storage/media/2022/01/otonom-transfer-arabalari-1.jpg',
        propert: [
          'Capacity: 5 ton to 100 tons',
          'Speed: Up to 30 m/min',
          'Steering: Front wheel steering',
          'Wheel Type: Rubber / Polyurethane',

          'Control: Remote control / Autonomous',
          'Power Source: Battery / Diesel',
          'Motors: PMAC / AC high efficiency motors',
          'Loading Table: On request',
          'Security: Laser and ultrasonic sensors, bumpers',
          'Dimensions: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
    ],
  },
  {
    id: 'automated stroge systems',
    title: 'AUTOMATED STORAGE SYSTEMS (ASRS)',
    url: 'automated-stroge-systems',
    desciription:
      'Thanks to the Automatic Storage Systems it has produced, FADA Engineering ensures the ergonomic, precise and safe storage of profiles, sheets, pipes, panels, heavy and geometrically difficult parts in industrial facilities. With the Warehouse Management Software it has developed, it offers various solutions for the automatic storage of heavy materials in your warehouses with minimum labor and maximum efficiency. Automatic storage systems, with their long and high structure, save space in the facilities, reduce your costs by automatically performing material transfer and material unloading within seconds. With its engineers who are experts in Storage Systems, FADA offers ideal storage solutions by closely following up-to-date technologies and developing innovative solutions according to your storage needs.',

    imgUrl: 'urll',
    product: [
      {
        id: '0001',
        type: 'automated stroge systems',
        title: 'single tower automated stroge system (STSS)',
        description: '',
        imgUrl: 'https://www.fada.com.tr/yuklenen/urunler/1643278941/k-1643278941-1643722063521.jpg',
        propert: [
          'Capacity: Up to 200 tons',
          'Shelf Capacity: Up to 5 tons',
          'Shelf Dimensions: 1 x 2 m / 1,5 x 3 m / 2 x 4 m / 2 x 6 m / On request',
          'Control: User-Friendly touch screen',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        options: [
          'Inventory management software',
          'ERP ıntegration',
          'Secondary loading / Unloading compartment',
          'Anti-Fall safety system',
          'Load-Cell system',
        ],
      },
      {
        id: '0002',
        type: 'automated stroge systems',
        title: 'double tower automated stroge system (DTSS)',
        description: '',
        imgUrl: 'urll',
        propert: [
          'Capacity: Up to 400 tons',
          'Shelf Capacity: Up to 5 tons',
          'Shelf Dimensions: 1 x 2 m / 1,5 x 3 m / 2 x 4 m / 2 x 6 m / On request',
          'Control: User-Friendly touch screen',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        options: [
          'Inventory management software',
          'ERP ıntegration',
          'Secondary loading / Unloading compartment',
          'Anti-Fall safety system',
          'Load-Cell System',
        ],
      },
      {
        id: '0003',
        type: 'automated stroge systems',
        title: ' multi-tower automated stroge system (MTSS)',
        description: '',
        imgUrl: 'https://www.fada.com.tr/yuklenen/urunler/1643278941/k-1643278941-1643722063521.jpg',
        propert: [
          'Capacity: Up to 1000 tons',
          'Shelf Capacity: Up to 5 tons',
          'Shelf Dimensions: 1 x 2 m / 1,5 x 3 m / 2 x 4 m / 2 x 6 m / On request',
          'Control: User-Friendly touch screen',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
        options: [
          'Inventory management software',
          'ERP ıntegration',
          'Secondary loading / Unloading compartment',
          'Anti-Fall safety system',
          'Load-Cell System',
        ],
      },
      {
        id: '0004',
        type: 'automated stroge systems',
        title: ' horizontel automated stroge system (HSS)',
        description: '',
        imgUrl: 'https://www.fada.com.tr/yuklenen/urunler/1643278941/k-1643278941-1643722063521.jpg',
        propert: [
          'Capacity: Up to 1000 tons',
          'Shelf Capacity: Up to 5 tons',
          'Shelf Dimensions: Up to 10 m',
          'Control:Semi or fully automatic control / ERP ıntegration- Database and inventory management software',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0005',
        type: 'automated stroge systems',
        title: ' sheet metal stroge system (SMSS)',
        description: '',
        imgUrl: 'https://www.fada.com.tr/yuklenen/urunler/1643281172/k-1643281172-16443908401758.png',
        propert: [
          'Capacity: Up to 40 tons',
          'Shelf Capacity: Up to 3 tons',
          'Shelf Dimensions: 1 x 2 m / 1,5 x 3 m / 2 x 4 m / On request',
          'Control:Semi or fully automatic control / ERP ıntegration- Database and inventory management software',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
      {
        id: '0006',
        type: 'automated stroge systems',
        title: ' profil stroge system (PSS)',
        description: '',
        imgUrl: 'https://www.fada.com.tr/yuklenen/urunler/1643281225/k-1643281225-16443941066916.png',
        propert: [
          'Capacity: Up to 500 tons',
          'Shelf Capacity: Up to 3 tons',
          'Shelf Dimensions: 0,4 x 0,4 x 6 m / On request',
          'Control: Manual',
          'Design: On request',
        ],
        certification: ['OHS regulations', 'EN standards', 'CE certificated'],
      },
    ],
  },
];
