import Head from 'next/head';
import React, { useRef } from 'react';
import { faYoutube, faFacebook, faLinkedin, faInstagram } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faPhone, faEnvelope, faLocationCrosshairs, faLocationDot } from '@fortawesome/free-solid-svg-icons';
import { Header } from '@/component/Header';
import { HeaderBottom } from '@/component/HeaderBottom';
import { Footer } from '@/component/footer/Footer';
import Breadcrumb from '@/component/BreadCrump';

const Contact5 = () => {
  const [state, setState] = React.useState({
    fullName: '',
    phone: '',
    email: '',
    message: '',
  });

  function handleChange(e: any) {
    if (e.target.files) {
      setState({ ...state, [e.target.name]: e.target.files[0] });
    } else {
      setState({ ...state, [e.target.name]: e.target.value });
    }
  }

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
  };

  const updateField = (e: { target: { name: any; value: any } }) => {
    setState({
      ...state,
      [e.target.name]: e.target.value,
    });
  };

  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <section className='bg-white dark:bg-gray-900'>
        <Header></Header>
        <HeaderBottom></HeaderBottom>

        <Breadcrumb></Breadcrumb>

        <div className='container lg:px-12 p-6 py-0 mx-auto '>
          <div className='lg:flex lg:items-center lg:-mx-1 '>
            <div className='lg:w-1/2 lg:mx-12   '>
              <h1 className='text-xl font-bold    max-sm:py-6    text-gray-700'>CONTACT</h1>

              <div className='mt-6 space-y-8 md:mt-8'>
                <p className='flex items-start -mx-2'>
                  <FontAwesomeIcon
                    className='w-6 h-6 mx-2 text-blue-500 dark:text-blue-400'
                    style={{}}
                    icon={faLocationDot}
                    size='1x'
                  ></FontAwesomeIcon>

                  <span className='mx-2 text-sm text-gray-700  w-72 dark:text-gray-400'>
                    Adliye Mahallesi, 1501. Sokak No:1 54580 Arifiye/Sakarya{' '}
                  </span>
                </p>

                <p className='flex items-start -mx-2 text-blue-500 dark:text-blue-400'>
                  <FontAwesomeIcon className='w-6 h-6 mx-2' style={{}} icon={faPhone} size='1x'></FontAwesomeIcon>

                  <span className='mx-2 text-sm text-gray-700 truncate w-72 dark:text-gray-400'>+90 264 275 20 01</span>
                </p>

                <p className='flex items-start -mx-2'>
                  <FontAwesomeIcon
                    className='w-6 h-6 mx-2 text-blue-500 dark:text-blue-400'
                    style={{}}
                    icon={faEnvelope}
                    size='1x'
                  ></FontAwesomeIcon>
                  <span className='mx-2 text-sm text-gray-700 truncate w-72 dark:text-gray-400'>info@fada.com.tr</span>
                </p>
              </div>

              <div className='mt-6 w-80 md:mt-8'>
                <div className='flex mt-4 -mx-1.5 '>
                  <a
                    className='mx-1.5 dark:hover:text-blue-400 text-gray-400 transition-colors duration-300 transform hover:text-blue-500'
                    href='#'
                  >
                    <FontAwesomeIcon className='w-8 h-8' style={{ width: '24px' }} icon={faLinkedin}></FontAwesomeIcon>
                  </a>

                  <a
                    className='mx-1.5 dark:hover:text-blue-400 text-gray-400 transition-colors duration-300 transform hover:text-blue-500'
                    href='#'
                  >
                    <FontAwesomeIcon className='w-8 h-8' style={{ width: '30px' }} icon={faYoutube}></FontAwesomeIcon>
                  </a>

                  <a
                    className='mx-1.5 dark:hover:text-blue-400 text-gray-400 transition-colors duration-300 transform hover:text-blue-500'
                    href='#'
                  >
                    <FontAwesomeIcon className='w-8 h-8' style={{ width: '24px' }} icon={faInstagram}></FontAwesomeIcon>
                  </a>

                  <a
                    className='mx-1.5 dark:hover:text-blue-400 text-gray-400 transition-colors duration-300 transform hover:text-blue-500'
                    href='#'
                  >
                    <FontAwesomeIcon className='w-8 h-8' style={{ width: '24px' }} icon={faFacebook}></FontAwesomeIcon>
                  </a>
                </div>
              </div>
              <br></br>
              <iframe
                src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6052.0953335546355!2d30.35661798282531!3d40.67291867064166!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14ccb343df644d99%3A0xea58b5ab7657ddb9!2sFADA%20M%C3%BChendislik!5e0!3m2!1str!2str!4v1680677556598!5m2!1str!2str'
                className='w-full'
                height='350'
                style={{ border: 0 }}
                loading='lazy'
              ></iframe>
            </div>

            <div className='mt-8 lg:w-2/5 h-max lg:mx-6'>
              <div className='w-full px-8 py-10 mx-auto overflow-hidden bg-white rounded-lg shadow-2xl dark:bg-gray-900 lg:max-w-xl shadow-gray-300/50 dark:shadow-black/50'>
                <h1 className='text-xl font-bold text-gray-700'>Write us</h1>

                <form onSubmit={handleSubmit} className='mt-6'>
                  <div className='flex-1'>
                    <label className='block mb-2 text-xs text-gray-600 dark:text-gray-200'>Full Name</label>
                    <input
                      name='fullName'
                      onChange={updateField}
                      type='text'
                      placeholder=''
                      pattern='[A-Za-z]+'
                      title='Full name should be digits  alphabets (a to z).'
                      className='block w-full px-5 py-3 mt-2 text-xs text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40'
                    />
                  </div>
                  <div className='flex-1 mt-6'>
                    <label className='block mb-2 text-xs text-gray-600 dark:text-gray-200'>Phone number</label>
                    <input
                      name='phone'
                      onChange={updateField}
                      type='number'
                      placeholder='5416945683'
                      className='block w-full px-5 py-3 mt-2 text-xs text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40'
                    />
                  </div>

                  <div className='flex-1 mt-6'>
                    <label className='block mb-2 text-xs text-gray-600 dark:text-gray-200'>Email address</label>
                    <input
                      name='email'
                      onChange={updateField}
                      type='email'
                      placeholder='johndoe@example.com'
                      className='block w-full px-5 py-3 text-xs mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40'
                    />
                  </div>

                  <div className='w-full mt-6'>
                    <label className='block mb-2 text-xs text-gray-600 dark:text-gray-200'>Message</label>
                    <textarea
                      name='message'
                      onChange={updateField}
                      className='block w-full h-32 px-5 py-3 mt-2 text-xs text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md md:h-48 dark:placeholder-gray-600 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-700 focus:border-blue-400 dark:focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40'
                      placeholder='Message'
                      maxLength={250}
                    ></textarea>
                    <div>
                      <div className=' mt-2 flex items-center'>
                        <input
                          id='link-checkbox'
                          type='checkbox'
                          value=''
                          className='w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600'
                        />
                        <label
                          htmlFor='link-checkbox'
                          className='ml-2 text-sm font-medium text-gray-900 dark:text-gray-300'
                        >
                          I agree with the{' '}
                          <a href='#' className='text-blue-600 dark:text-blue-500 hover:underline'>
                            terms and conditions
                          </a>
                          .
                        </label>
                      </div>
                    </div>
                  </div>

                  <button
                    type='submit'
                    className='w-full px-6 py-3 mt-6 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-500 rounded-md hover:bg-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-50'
                  >
                    get in touch
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer></Footer>
    </>
  );
};

export default Contact5;
